#!/usr/bin/env bash
#
# Install all the basics, only need this one the first time I think

echo "Installing homebrew"
ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"

echo "Installing homebrew tools"
brew install apple-gcc42 autoconf automake cloog cmake composer cscope ecj freetype gdbm gettext git glib gmp icu4c irssi isl jpeg libffi libgpg-error libksba libmpc libpng libtool libxml2 libxslt libyaml makedepend mcrypt mercurial mhash mpfr mysql node openssl ossp-uuid pcre php55 php55-intl php55-mcrypt pkgconfig postgresql python readline scons sqlite subversion unixodbc wget xz zlib zsh ctags tmux
brew install macvim --override-system-vim

echo "Installing Oh My ZSH"
curl -L http://install.ohmyz.sh | sh

echo "Installing RVM"
\curl -sSL https://get.rvm.io | bash -s stable

echo "Creating some symlinks"
mkdir ~/.old_dotfiles
mv ~/.bashrc ~/.old_dotfiles/.bashrc
mv ~/.bash_profile ~/.old_dotfiles/.bash_profile
mv ~/.gitconfig ~/.old_dotfiles/.gitconfig
mv ~/.gitignore_global ~/.old_dotfiles/.gitignore_global
mv ~/.gemrc ~/.old_dotfiles/.gemrc
mv ~/.rvmrc ~/.old_dotfiles/.rvmrc
mv ~/.vimrc ~/.old_dotfiles/.vimrc
mv ~/.gvimrc ~/.old_dotfiles/.gvimrc
mv ~/.zlogin ~/.old_dotfiles/.zlogin
mv ~/.zshrc ~/.old_dotfiles/.zshrc
mv ~/.tmux.conf ~/.old_dotfiles/.tmux.conf
ln -s ~/.dotfiles/bash/bashrc ~/.bashrc
ln -s ~/.dotfiles/bash/bash_profile ~/.bash_profile
ln -s ~/.dotfiles/git/gitconfig ~/.gitconfig
ln -s ~/.dotfiles/git/gitignore_global ~/.gitignore_global
ln -s ~/.dotfiles/rvm/gemrc ~/.gemrc
ln -s ~/.dotfiles/rvm/rvmrc ~/.rvmrc
ln -s ~/.dotfiles/vim/vimrc ~/.vimrc
ln -s ~/.dotfiles/vim/gvimrc ~/.gvimrc
ln -s ~/.dotfiles/zsh/zlogin ~/.zlogin
ln -s ~/.dotfiles/zsh/zshrc ~/.zshrc
ln -s ~/.dotfiles/tmux/tmux.conf ~/.tmux.conf
