#!/usr/bin/env sh
#
# Install all the basics, only need this one the first time I think

echo "Installing homebrew"
ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"

echo "Installing homebrew tools"
brew install awscli \
             chromedriver \
             ctags \
             git \
             irssi \
             mysql \
             perl \
             postgresql \
             python \
             python3 \
             rabbitmq \
             rbenv \
             reattach-to-user-namespace \
             redis \
             ruby \
             the_silver_searcher \
             tmux \
             wget \
             yarn \
             zsh

echo "Installing neovim"
brew tap neovim/neovim && brew install neovim

echo "Cleaning up homebrew"
brew cleanup

echo "Installing Oh My ZSH"
curl -L http://install.ohmyz.sh | sh

echo "Creating some symlinks"
mkdir ~/.old_dotfiles
mv ~/.bashrc ~/.old_dotfiles/.bashrc
mv ~/.bash_profile ~/.old_dotfiles/.bash_profile
mv ~/.gitconfig ~/.old_dotfiles/.gitconfig
mv ~/.gitignore_global ~/.old_dotfiles/.gitignore_global
mv ~/.gemrc ~/.old_dotfiles/.gemrc
mv ~/.rvmrc ~/.old_dotfiles/.rvmrc
mv ~/.vimrc ~/.old_dotfiles/.vimrc
mv ~/.gvimrc ~/.old_dotfiles/.gvimrc
mv ~/.zlogin ~/.old_dotfiles/.zlogin
mv ~/.zshrc ~/.old_dotfiles/.zshrc
mv ~/.tmux.conf ~/.old_dotfiles/.tmux.conf
ln -s ~/.dotfiles/bash/bashrc ~/.bashrc
ln -s ~/.dotfiles/bash/bash_profile ~/.bash_profile
ln -s ~/.dotfiles/git/gitconfig ~/.gitconfig
ln -s ~/.dotfiles/git/gitignore_global ~/.gitignore_global
ln -s ~/.dotfiles/ruby/gemrc ~/.gemrc
ln -s ~/.dotfiles/vim/vimrc ~/.vimrc
ln -s ~/.dotfiles/vim/gvimrc ~/.gvimrc
ln -s ~/.dotfiles/zsh/zlogin ~/.zlogin
ln -s ~/.dotfiles/zsh/zshrc ~/.zshrc
ln -s ~/.dotfiles/tmux/tmux.conf ~/.tmux.conf
